linkedin/li-apache-kafka-clients

circle.yml

This should be from a clean branch this time.

Circleci test result integration on a clean branch.

---

README.md

Cut and paste directions for adding the jars as a dependency to your gradle project.

Document how to add the artifact repository containing the li-apache-kafka-jars.

---

src/main/java/com/linkedin/kafka/clients/consumer/ConsumerRecordsProcessor.java
src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java

This fixes an issue that OffsetNotTrackedException is thrown if user tries to commit a first delivered message offset explicitly.

Fix commit with user provided offset map containing first tracked offset.

---

src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumer.java
src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerConfig.java
src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java
src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessResult.java
src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessor.java
src/main/java/com/linkedin/kafka/clients/largemessage/MessageSplitterImpl.java
src/main/java/com/linkedin/kafka/clients/largemessage/errors/ConsumerRecordsProcessingException.java
src/main/java/com/linkedin/kafka/clients/largemessage/errors/RecordProcessingException.java
src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java
src/test/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessorTest.java

Issue#43 Handle exception in the message processing

---

.circleci/config.yml
gradle.properties
settings.gradle

trigger a release

---

.circleci/config.yml
.circleci/publish.sh
.circleci/publishOnCommitMsg.sh

docs - https://circleci.com/docs/2.0/workflows/#git-tag-job-execution

Add release on tag for circleci

---

integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java

Signed-off-by: radai-rosenblatt <radai.rosenblatt@gmail.com>

fix flaky tests around offset commits

---

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessor.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerImpl.java

Signed-off-by: radai-rosenblatt <radai.rosenblatt@gmail.com>

timeout support for close and better logging of close

---

integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessor.java

code was check-pointing the offset(s) of the last msg that was ever delivered. there may never have been such a msg...

fix bug where committed offsets were not making progress when all msgs are too large

---

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducer.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerImpl.java

It was accidentally removed in PR #100.

Add back LiKafkaProducer.partitionsFor() that takes a set of topics

---

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/metadataservice/MarioMetadataServiceClient.java

If needed, retry will be implemented in MarioClient side.

Federated Clients: remove retry logic from MarioMetadataServiceClient

---

build.gradle
integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java
integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerIntegrationTest.java
kafka-test-harness/build.gradle
li-apache-kafka-clients/build.gradle
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerImpl.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/LiKafkaClientsUtils.java
li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/utils/LiKafkaClientsUtilsTest.java

also switch to depending on linkedin's kafka fork

supply known library versions to instrumented client

---

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessor.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/LiKafkaClientsUtils.java

add records-skipped metric

---

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/auditing/abstractimpl/AbstractAuditor.java

catch exception on auditor close

---

build.gradle

bump mario

---

build.gradle
integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java
li-apache-kafka-clients/build.gradle

Signed-off-by: Radai Rosenblatt <rrosenbl@rrosenbl-ld1.linkedin.biz>

update kafka clients and mario client, switch to shaded mario client

---

build.gradle
li-apache-kafka-clients/build.gradle
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/common/MetricsProxy.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/CompositeCollection.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/CompositeIterator.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/CompositeMap.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/CompositeSet.java
li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/utils/CompositeMapTest.java

Signed-off-by: Radai Rosenblatt <rrosenbl@rrosenbl-ld1.linkedin.biz>

improve the performance of composing client metrics in liConsumer

---

build.gradle

Signed-off-by: Radai Rosenblatt <rrosenbl@rrosenbl-ld1.linkedin.biz>

update mario client

---

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerImpl.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaInstrumentedProducerImpl.java

Change alert level of mario client connection timeout from error to warning for LiKafkaInstrumentedConsumer

Change alert level of mario client connection timeout from error to warning for LiKafkaInstrumentedConsumer

---

build.gradle
integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerIntegrationTest.java
integration-tests/src/test/java/com/linkedin/kafka/clients/producer/LiKafkaInstrumentedProducerIntegrationTest.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerImpl.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaInstrumentedProducerImpl.java

1. Bump mario to enable TopicQuery
2. Fix integration tests to use new SimpleClient api

Bump mario from 0.0.29 to 0.0.34 to enable TopicQuery

---

integration-tests/src/test/java/com/linkedin/kafka/clients/producer/LiKafkaProducerIntegrationTest.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerImpl.java

_t header should be treated immutable and should not be modified

Make TIMESTAMP (_t) header immutable

---

build.gradle

check details here:
https://github.com/linkedin/kafka/pull/115

Update kafka version to 2.0.0.32 to pick up passthrough patch

---

integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerIntegrationTest.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerConfig.java
li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java

Reverts linkedin/li-apache-kafka-clients#193
For https://jira01.corp.linkedin.com:8443/browse/LIKAFKA-36373

[LI-HOTFIX] Revert passthroughConsumerRecord

---

build.gradle

Contains the revert of passthrough patch

[LI-HOTFIX] Upgrade kafka to 2.0.0.37
