build.gradle, gradle.properties, src/test/scala/com/linkedin/kafka/clients/utils/tests/TestUtils.scala
for great justice
Signed-off-by: rrosenbl <rrosenblatt@linkedin.com>
=> drop scala daemon, disable kafka test broker log compaction to save memory

src/main/java/com/linkedin/kafka/clients/largemessage/LargeMessageBufferPool.java, src/main/java/com/linkedin/kafka/clients/utils/QueuedMap.java, src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java
We saw a case that the used buffer recorded by LargeMessageBufferPool was none zero while there was no large message buffered. Adding the sanity check logic and hopefully we can catch the issue.
=> Add sanity check logic to the message eviction.

src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java, src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerSSLIntegrationTest.java, src/test/java/com/linkedin/kafka/clients/producer/LiKafkaProducerIntegrationTest.java, src/test/java/com/linkedin/kafka/clients/producer/LiKafkaProducerSSLIntegrationTest.java, src/test/scala/com/linkedin/kafka/clients/utils/tests/AbstractKafkaClientsIntegrationTestHarness.scala, src/test/scala/com/linkedin/kafka/clients/utils/tests/AbstractKafkaIntegrationTestHarness.scala
We currently do not have any SSL testing in the integration test harness. This patch rectifies this gap.
=> Add SSL support to integration tests

src/main/java/com/linkedin/kafka/clients/largemessage/MessageSplitterImpl.java, src/test/java/com/linkedin/kafka/clients/producer/LiKafkaProducerIntegrationTest.java
The MessageSplitterImpl computes the number of segments as zero and then returns an empty list of segments.  This change causes the zero length value to be handled the same was a null value.  A producer unit test has been added for this corner case.
=> Fix IndexOutputOfBoundsException when sending records with zero length values.

integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessor.java
When the highwatermark is still higher than the committed offset we still want to commit an offset that is higher than the first offset we started to consume at.
A unit test for this has been added.
=> Always make progress on commits.

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java
Change calls to the underlying consumer.position() to the position() that is aware of resets.
Refactor offset invalid offset handling into common code.
=> Handle invalid offsets in a uniform manner.

integration-tests/src/test/java/com/linkedin/kafka/clients/auditing/ConfigureAuditorTest.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerImpl.java
This patch fixes the following issues:
- Close() with timeout didn't calculate remaining time ms correctly.
- Close() with timeout should set isClosed to true.
- Close() should have the same behavior as close(MAX_LONG).
=> Fix the calculation of remaining waiting time when closing producer

integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java, integration-tests/src/test/java/com/linkedin/kafka/clients/utils/LiKafkaClientsTestUtils.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerRebalanceListener.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiOffsetResetStrategy.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessor.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/LargeMessageBufferPool.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/MessageAssembler.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/MessageAssemblerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducer.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerImpl.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessorTest.java
Major ones are:
-  Add bounded flush to LiKafkaProducer
- Expire large message segments when normal messages arrive.
-  LICLOSEST implementation & integration tests (introduced `LiOffsetResetStrategy` to avoid using `String`) 
- Don't retrieve the consumer high watermark for every partition on every offset commit.
=> Porting all fixes from linkinedin. 

build.gradle, integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java, integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerSSLIntegrationTest.java, integration-tests/src/test/java/com/linkedin/kafka/clients/producer/LiKafkaProducerSSLIntegrationTest.java, kafka-test-harness/src/main/java/com/linkedin/kafka/clients/utils/tests/AbstractKafkaClientsIntegrationTestHarness.java, kafka-test-harness/src/main/java/com/linkedin/kafka/clients/utils/tests/AbstractKafkaIntegrationTestHarness.java, kafka-test-harness/src/main/java/com/linkedin/kafka/clients/utils/tests/EmbeddedBroker.java, kafka-test-harness/src/main/java/com/linkedin/kafka/clients/utils/tests/EmbeddedBrokerBuilder.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumer.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducer.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/largemessage/LageMessageCallbackTest.java
The following changes have been made in addition to bumping up the Kafka version to pull in:
- LiKafkaConsumerImpl implements new methods in the KafkaConsumer API, including ones that introduce timeouts for existing operations like position, committed, etc.
- org.apache.kafka.common.protocol.Security is under the package, org.apache.kafka.common.security.auth, in 2.0
- Redundant API declarations in LiKafkaProducer and LiKafkaConsumer have been removed.
=> Pull in Kafka 2.0 clients

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/MessageSplitterImpl.java
Even though we are passing topic here to serialize method, the segment itself should be topic independent. This fix was missed when porting all changes from Linkedin.
=> Make topic name accessible in the MessageSplitterImpl

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerConfig.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerImpl.java
1. Use LongAdder instead of AtomicInteger, which is more performant.
2. Use the large.message.segment.wrapping.required property to control whether or not wrap a normal-sized message in a large message segment
(The default value is set to false for now, to match the previous behavior.)
3. Use the min of max.message.segment.bytes and max.request.size for the max message segment size for large message.
4. Use an exception instead of an assert
=> Various improvements to LiKafkaProducerImpl.

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaFederatedConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/metadataservice/MetadataServiceClient.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaFederatedProducerImpl.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaFederatedConsumerImplTest.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/consumer/MockLiKafkaConsumer.java
Also removed an unused class from LiKafkaFederatedProducerImpl.java.
=> Federated Clients: implement LiKafkaFederatedConsumerImpl#assign() and assignment()

integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java, kafka-test-harness/src/main/java/com/linkedin/kafka/clients/utils/tests/KafkaTestUtils.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessResult.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessorTest.java
poll() keeps a cache of exceptions per partition and throws exception in subsequent poll() call.
poll() also seek offset past exception assuming next poll() will throw exception.
This can lead to message loss if the user does not call poll() and commits offsets.
The fix stores the current offset and resume offset along with the exception. On exception,
it seeks to current offset (before exception) along with resume offset (current + 1).
On next poll(), poll() will seek to resume offset and throw exception and the user can decide
on either ignoring it which will skip the offset or exit.
On next seek*(), will throw an IllegalStateException and seeking to resume offsets, leaving the
decision to user to continue poll() or crash.
On exit, the user can safely commit offsets it consumed …
=> fix message loss between poll() and close()

build.gradle, li-apache-kafka-clients/build.gradle, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/common/LiKafkaFederatedClient.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/common/LiKafkaFederatedClientType.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaFederatedConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/metadataservice/MarioCommandCallbackImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/metadataservice/MarioMetadataServiceClient.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/metadataservice/MetadataServiceClient.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaFederatedProducerImpl.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/metadataservice/MarioMetadataServiceClientTest.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/producer/LiKafkaFederatedProducerImplTest.java
Add federated producer config reload support, basically flush and close all the per-cluster producers in another thread upon receiving the reload config command.
Currently just use synchronized methods for now, will modify to rwlock later.
=> Add federated producer config reload support

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaFederatedConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/metadataservice/MarioCommandCallbackImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaFederatedProducerImpl.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaFederatedConsumerImplTest.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/producer/LiKafkaFederatedProducerImplTest.java
Add federated consumer config reload support, basically same flow as federated producer, i.e. upon receiving the reload config command, spin another thread, close the consumer, then apply the new configs. Assumption here is that all other consuming methods will be creating per-cluster consumers, so we don't re-create per-cluster consumers during reload config.
=> Add federated consumer reload config support

kafka-test-harness/src/main/java/com/linkedin/kafka/clients/utils/tests/AbstractKafkaIntegrationTestHarness.java, kafka-test-harness/src/test/java/com/linkedin/kafka/clients/utils/tests/KafkaIntegrationTestHarnessTest.java
- killBroker(id)
- killRandomBroker()
- restartDeadBrokers()
Adds some methods that were not ported from the scala based test harness
previously.
=> Added addtional methods to 'AbstractKafkaIntegrationTestHarness'

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaFederatedConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaFederatedProducerImpl.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaFederatedConsumerImplTest.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/producer/LiKafkaFederatedProducerImplTest.java
Re-create producers and consumers as part of config reload command instead of lazy construction to avoid delay of errors and user impact.
=> recreate producers and consumers during config reload command

build.gradle, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaFederatedConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/metadataservice/MarioCommandCallbackImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/metadataservice/MarioMetadataServiceClient.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/metadataservice/MetadataServiceClient.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaFederatedProducerImpl.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaFederatedConsumerImplTest.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/metadataservice/MarioMetadataServiceClientTest.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/producer/LiKafkaFederatedProducerImplTest.java
Adds support for config push at boot up time. When federated client registers itself to Mario, Mario will return a set of configs it wants federated client to apply at boot up time. This set of configs is saved first then applied when actually creating per-cluster clients.
=> Add support for config push at boot up time

build.gradle
Bump up mario version to avoid leaking log4j2 bindings to downstream dependencies.
=> Bump up mario version to 0.0.9

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaFederatedProducerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducer.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerImpl.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/producer/MockLiKafkaProducer.java
There is `partitionFor` API override in `LiKafkaProducer` interface that accepts a `Set` of topic names as an argument. It is however, not implemented in anywhere. 
* I also verified the internal LinkedIn specific implementations. 
* I don't see the API in Apache Kafka. So, the `TODO` comment near the API definition doesn't make sense.
=> Removing partitionsFor API that has no implementation 

build.gradle, integration-tests/build.gradle, integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java, integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerIntegrationTest.java, integration-tests/src/test/java/com/linkedin/kafka/clients/producer/LiKafkaInstrumentedProducerIntegrationTest.java, kafka-test-harness/src/main/java/com/linkedin/kafka/clients/utils/tests/AbstractKafkaClientsIntegrationTestHarness.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/common/MetricsProxy.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaInstrumentedProducerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/LiKafkaClientsUtils.java
this PR adds "instrumented" kafka clients - these are decorators around kafka clients that maintain a connection to a MDS (conductor) and are capable of basic "remote control" - currently only config overrides.
=> initial implementation of instrumented clients

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaInstrumentedProducerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerImpl.java
This is temporary until KAFKA-7711 is fixed in upstream.
=> Add the bounded flush implementation to LiKafkaInstrumentedProducer

buildSrc/build.gradle
see https://github.com/jfrog/build-info/issues/171
=> bump bintray library to work with newer gradle

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessor.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/Constants.java, li-apache-kafka-clients/src/test/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessorTest.java
What and why?
For every record consumed from li-apache-kafka-client consumer, the record will be annotated with a safe offset header such that systems like brooklin aren't forced to use LiKafkaConsumer interface (which has #safeOffsets() api) but instead can just work with Consumer interface and the headers.
=> Introduce safe offset record header

integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerIntegrationTest.java, kafka-test-harness/src/main/java/com/linkedin/kafka/clients/utils/tests/EmbeddedBrokerBuilder.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/CloseableLock.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/KafkaConsumerLock.java
note that vanilla clients would throw an exception on the thread calling close() in this case.
=> make instrumented consumer behave the same as vanilla consumer around concurrent poll and close

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/auditing/abstractimpl/AbstractAuditor.java
If the timeout passed to auditingKafkaProducer#close() method is very short, it can so happen that the producer might get closed before all the audit counts are flushed raising _IllegalArgumentException_.
This change logs such exceptions during the shutdown as a warning instead of an error.
=> Log the exception as warning for Auditor during shutdown.

build.gradle
Update kafka version to 2.0.0.25 to include fix for KAFKA-8950 - KafkaConsumer stops fetching
=> Update kafka version to 2.0.0.25

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessor.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerImpl.java
Compression/Decompression will be implemented by extending Extended{Serializer, Deserializer} interface and adding a delegate avro serializer/deserializer. So Serde with (de)compression will be passed in from "Linkedin bits" and used in the client. At produce time, we first serialize and then compress, at consume time, we first decompress then serialize.
=> use extended serde interface for sdc testing

integration-tests/src/test/java/com/linkedin/kafka/clients/largemessage/LargeMessageIntegrationTest.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/common/LargeMessageHeaderValue.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessor.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/MessageSplitterImpl.java
`LargeMessageHeaderValue` is missing `messageSizeInBytes`, which indicates the size of the original message. This is useful to validate the segments during assembling on the consumer side. <br/>
With the existing code, we will see failures when we try to assemble based on the metadata from the large message header.  Not sure why this left out in the original patch that introduced the header value. Adding it now to ensure that segment validation can be done.
=> Adding original message size to the large message header value

integration-tests/src/test/java/com/linkedin/kafka/clients/largemessage/LargeMessageIntegrationTest.java, integration-tests/src/test/java/com/linkedin/kafka/clients/producer/LiKafkaProducerIntegrationTest.java, integration-tests/src/test/java/com/linkedin/kafka/clients/utils/LiKafkaClientsTestUtils.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/LiKafkaClientsUtils.java
Additional methods provide easier way to access special header.
=> Add special header accessors under li-apache-kafka-clients

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/ConsumerRecordsProcessor.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/DeliveredMessageOffsetTracker.java
In order to identify a partition "stall" due to partial large message assembly (and not due to other problems in the consumer), we are introducing a metric called "consumer offset watermark span".  For each partition, the span distance is computed as (`watermark minus safeOffset`). Consumer offset watermark span is defined as the sum of all span distance for assigned partitions that have currently undelivered large messages in the consumer. 
When the consumer is progressing with no partial large messages in buffer, its span distance should be 0 because watermark is same as safeOffset.
=> Added a new consumer metric - consumerOffsetWatermarkSpan to represent "distance between the safe offset and watermark"

integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerIntegrationTest.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerConfig.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java
Add an exception.on.invalid.offset config to allow throw the InvalidOffsetException even when auto.offset.reset for LiKafkaConsumer is set to some policy (earliest/latest/liclosest). This is to allow users to handle this exception while let LiKafkaConsumer deal with the internal state of large message.
This is just a temporary solution and will be discarded when large message support has been refactored
=> Add exception.on.invalid.offset config to allow throwing exception when auto.offset.reset is set to some policy

build.gradle
Bump liKafkaVersion from 2.0.0.25 to 2.0.0.27 to include MM passthrough fix revert.
There was a patch to enable passthrough work between msg format v1 and v2, but BMM/KMM is seeing perf issues with the patch. Due to lack of snapshot debugging, we have to revert that patch to verify and unblock BMM/KMM.
=> Bump kafka version to include MM passthrough fix revert

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/MessageSplitterImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerConfig.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/Constants.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/PrimitiveEncoderDecoder.java
This PR adds `enableRecordHeader` config in producer. When it is true, producer will add a new field in the record header and skip segment serialization in MsgSplitter. The type(version) field in LMHeaderValue will be set to V3 as well, which means we will only use record header based LM support. 
By detecting the type(version) field in LMHeaderValue, consumer  can choose if it should use segment deserialization in MsgAssembler. So we do not need to add this config in consumer side.
=> Add enableRecordHeader config in producer

integration-tests/src/test/java/com/linkedin/kafka/clients/largemessage/LargeMessageIntegrationTest.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/MessageSplitterImpl.java
The previous (pr)[https://github.com/linkedin/li-apache-kafka-clients/pull/184] introduce a bug of   wrongly using payload.array() instead of using segment.payloadArray().
This pr is to fix that problem and add a new integration test for that config
=> add test and fix a bug of using  payload.array()

build.gradle, integration-tests/build.gradle, integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerIntegrationTest.java, integration-tests/src/test/java/com/linkedin/kafka/clients/largemessage/LargeMessageIntegrationTest.java, integration-tests/src/test/java/com/linkedin/kafka/clients/producer/LiKafkaInstrumentedProducerIntegrationTest.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/common/InstrumentedClientLoggingHandler.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/largemessage/MessageSplitterImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaInstrumentedProducerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/utils/LiKafkaClientsUtils.java
Added new metric( _offsetInvalidOrOutRangeCounter) into LiKafkaConsumerImpl to count number of OffsetOutOfRange exceptions under following cases with liclosest reset strategy.
**1. fetchedOffset <  Log Start Offset (LSO)
2. fetchedOffset <= Log End Offset (LEO)**
This metric can be used as indicator to estimate the potential data loss upon the LiKafkaConsumer client reseting the offset to "liclosest"
=> Add new LiKafkaConsumerImpl metric - _offsetInvalidOrOutRangeCounter to estimate the potential data loss

li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaInstrumentedProducerImpl.java
Fix race condition in LiKafkaInstrumentedProducerImpl when two threads calling close in send callback.
Problem:
BMM has a use case of calling producer.close in send callback when send fails, with current code, there could still be race conditions given the following sequence:
Both Thread 1 and Thread 2 are calling same producer.send(tp, cbk) and fails, and tries to call producer.close in the cbk:
Thread 1: Hold closeLock, (release Read lock,) wait on Write lock
Thread 2: Hold Read lock, wait on closeLock.
Thus deadlock.
Fix:
Ensure same ordering of acquiring/releasing locks when proceedClose(), i.e. first release all Read locks held by current thread, then grab Write lock to proceed closing.
=> Fix race condition in LiKafkaInstrumentedProducerImpl

build.gradle
Bump kafka from 2.0.0.28 to 2.0.0.29 to pick up oss fix for stale cluster metadata when removing all brokers from one cluster and add the broker(s) to another cluster.
=> Bump kafka version to pick up fix for cluster id mismatch

integration-tests/src/test/java/com/linkedin/kafka/clients/producer/LiKafkaInstrumentedProducerIntegrationTest.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaInstrumentedProducerImpl.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducerImpl.java
This request aims to fixing li-apache-kafka-clients producer flush() contract different in vanilla client.
- Removed verifyOpen() from flush() and flush(long timeout, TimeUnit timeUnit).
- Peeled InvocationTargetException and re-throw vanilla client exception.
- Added flush() integration test.
=> Fix Kafka flush() contract different in vanilla client v/s li-apache-kafka-clients

integration-tests/src/test/java/com/linkedin/kafka/clients/consumer/LiKafkaInstrumentedConsumerIntegrationTest.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerConfig.java, li-apache-kafka-clients/src/main/java/com/linkedin/kafka/clients/consumer/LiKafkaConsumerImpl.java
Problem: When BMM testing the passthrough feature, it turns out during ConsumerRecordsProcessor.handleConsumerRecord, we are transforming the underlying PassthroughConsumerRecord into ConsumerRecord type, thus causing some type cast issue in the caller.
Fix: When passthrough is enabled on consumer side, ideally we should bypass the large message processing part and just return the consumed record directly to the caller.
Test: added integration test to verify the return record type when enable.shallow.iterator is set to true for consumer.
=> Bypass large message processing when passthrough is enabled for consumer
